#!/bin/bash -e
#
# ==============================================================================
# PAQUETE: kit-servicios-client
# ARCHIVO: postinst
# DESCRIPCIÓN: Configura el sistema despues la instalación del paquete.
# COPYRIGHT:
#  (C) 2016 Victor Pino <victopin0@gmail.com>
# LICENCIA: GPL3
# ==============================================================================
#
# Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo los
# términos de la Licencia Pública General de GNU (versión 3).


case "$1" in
    configure)

        serviceCommand() {
            if service --status-all | grep -Fq ${1}; then
                service ${1} ${2}
            fi
        }
       
        # Source debconf library.
        . /usr/share/debconf/confmodule

        serviceCommand ssh restart || true
                
    ;;

    abort-upgrade|upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
